// Game library types and complete game catalog (100 games)

export type Difficulty = 'easy' | 'medium' | 'hard';
export type AgeGroup = 'kids' | 'seniors' | 'all-ages';

export interface Game {
    id: string;
    name: string;
    description: string;
    category: string;
    ageGroup: AgeGroup;
    difficulty: Difficulty;
    thumbnail: string;
    estimatedPlayTime: number; // minutes
    tags: string[];
    premium?: boolean; // For special/featured games
}

// Complete 100-game catalog
export const GAMES: Game[] = [
    // ===== SENIOR GAMES (50) =====

    // Brain Training & Logic (15 games)
    {
        id: 'sudoku-classic',
        name: 'Sudoku Classic',
        description: 'Fill the 9x9 grid with numbers 1-9',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/sudoku.jpg',
        estimatedPlayTime: 8,
        tags: ['logic', 'numbers', 'puzzle'],
        premium: true,
    },
    {
        id: 'sudoku-mini',
        name: 'Mini Sudoku',
        description: '6x6 Sudoku for a quicker challenge',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'easy',
        thumbnail: '/games/sudoku-mini.jpg',
        estimatedPlayTime: 3,
        tags: ['logic', 'numbers', 'quick'],
    },
    {
        id: 'memory-match',
        name: 'Memory Match',
        description: 'Flip cards and match pairs',
        category: 'brain-training',
        ageGroup: 'all-ages',
        difficulty: 'easy',
        thumbnail: '/games/memory.jpg',
        estimatedPlayTime: 3,
        tags: ['memory', 'concentration'],
        premium: true,
    },
    {
        id: 'pattern-master',
        name: 'Pattern Master',
        description: 'Identify and complete visual patterns',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/patterns.jpg',
        estimatedPlayTime: 4,
        tags: ['visual', 'logic', 'patterns'],
    },
    {
        id: 'number-sequence',
        name: 'Number Sequence',
        description: 'Find the missing number in the sequence',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/sequence.jpg',
        estimatedPlayTime: 3,
        tags: ['numbers', 'logic'],
    },
    {
        id: 'spot-difference',
        name: 'Spot the Difference',
        description: 'Find differences between two images',
        category: 'brain-training',
        ageGroup: 'all-ages',
        difficulty: 'easy',
        thumbnail: '/games/difference.jpg',
        estimatedPlayTime: 5,
        tags: ['visual', 'observation'],
    },
    {
        id: 'logic-grid',
        name: 'Logic Grid Puzzles',
        description: 'Solve logical deduction puzzles',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'hard',
        thumbnail: '/games/logic-grid.jpg',
        estimatedPlayTime: 10,
        tags: ['logic', 'deduction'],
    },
    {
        id: 'mental-math',
        name: 'Mental Math',
        description: 'Quick arithmetic practice',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/mental-math.jpg',
        estimatedPlayTime: 5,
        tags: ['math', 'speed', 'numbers'],
    },
    {
        id: 'memory-cards-advanced',
        name: 'Memory Champion',
        description: 'Advanced memory game with 24 cards',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'hard',
        thumbnail: '/games/memory-hard.jpg',
        estimatedPlayTime: 6,
        tags: ['memory', 'challenge'],
    },
    {
        id: 'kakuro',
        name: 'Kakuro',
        description: 'Number crossword puzzle',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'hard',
        thumbnail: '/games/kakuro.jpg',
        estimatedPlayTime: 12,
        tags: ['numbers', 'logic', 'math'],
    },
    {
        id: 'nonogram',
        name: 'Nonogram',
        description: 'Picture logic puzzles',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/nonogram.jpg',
        estimatedPlayTime: 8,
        tags: ['logic', 'visual', 'picture'],
    },
    {
        id: 'brain-teasers',
        name: 'Brain Teasers',
        description: 'Challenging riddles and puzzles',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'hard',
        thumbnail: '/games/teasers.jpg',
        estimatedPlayTime: 4,
        tags: ['logic', 'riddles'],
    },
    {
        id: 'color-match',
        name: 'Color Memory',
        description: 'Remember and match color sequences',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/color-match.jpg',
        estimatedPlayTime: 4,
        tags: ['memory', 'colors', 'sequence'],
    },
    {
        id: 'number-bonds',
        name: 'Number Bonds',
        description: 'Find pairs that add up to target',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'easy',
        thumbnail: '/games/bonds.jpg',
        estimatedPlayTime: 3,
        tags: ['math', 'addition'],
    },
    {
        id: 'spatial-reasoning',
        name: 'Spatial Puzzles',
        description: 'Rotate and match 3D shapes',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/spatial.jpg',
        estimatedPlayTime: 5,
        tags: ['spatial', '3d', 'shapes'],
    },

    // Classic Card & Board Games (15 games)
    {
        id: 'solitaire-klondike',
        name: 'Solitaire (Klondike)',
        description: 'The classic patience card game',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/solitaire.jpg',
        estimatedPlayTime: 6,
        tags: ['cards', 'classic'],
        premium: true,
    },
    {
        id: 'solitaire-spider',
        name: 'Spider Solitaire',
        description: 'Two-deck solitaire variation',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'hard',
        thumbnail: '/games/spider.jpg',
        estimatedPlayTime: 10,
        tags: ['cards', 'challenge'],
    },
    {
        id: 'solitaire-freecell',
        name: 'FreeCell',
        description: 'Strategic solitaire with open cells',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/freecell.jpg',
        estimatedPlayTime: 7,
        tags: ['cards', 'strategy'],
    },
    {
        id: 'mahjong-solitaire',
        name: 'Mahjong Solitaire',
        description: 'Match traditional mahjong tiles',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/mahjong.jpg',
        estimatedPlayTime: 8,
        tags: ['tiles', 'matching'],
        premium: true,
    },
    {
        id: 'checkers',
        name: 'Checkers vs AI',
        description: 'Classic checkers against computer',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/checkers.jpg',
        estimatedPlayTime: 10,
        tags: ['board', 'strategy', 'ai'],
    },
    {
        id: 'chess-puzzles',
        name: 'Chess Puzzles',
        description: 'Solve chess endgame scenarios',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'hard',
        thumbnail: '/games/chess.jpg',
        estimatedPlayTime: 5,
        tags: ['chess', 'strategy', 'puzzle'],
    },
    {
        id: 'dominoes',
        name: 'Dominoes',
        description: 'Match domino tiles end to end',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'easy',
        thumbnail: '/games/dominoes.jpg',
        estimatedPlayTime: 8,
        tags: ['tiles', 'matching'],
    },
    {
        id: 'backgammon',
        name: 'Backgammon',
        description: 'Ancient board game strategy',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/backgammon.jpg',
        estimatedPlayTime: 12,
        tags: ['board', 'strategy', 'dice'],
    },
    {
        id: 'reversi',
        name: 'Reversi (Othello)',
        description: 'Flip opponent pieces to win',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/reversi.jpg',
        estimatedPlayTime: 10,
        tags: ['board', 'strategy'],
    },
    {
        id: 'connect-four',
        name: 'Connect Four',
        description: 'Get four in a row to win',
        category: 'classic-games',
        ageGroup: 'all-ages',
        difficulty: 'easy',
        thumbnail: '/games/connect4.jpg',
        estimatedPlayTime: 5,
        tags: ['board', 'strategy'],
    },
    {
        id: 'minesweeper',
        name: 'Minesweeper',
        description: 'Clear the board without hitting mines',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/minesweeper.jpg',
        estimatedPlayTime: 6,
        tags: ['logic', 'classic'],
    },
    {
        id: 'hearts',
        name: 'Hearts',
        description: 'Classic trick-taking card game',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/hearts.jpg',
        estimatedPlayTime: 10,
        tags: ['cards', 'strategy'],
    },
    {
        id: 'gin-rummy',
        name: 'Gin Rummy',
        description: 'Form sets and runs of cards',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/gin.jpg',
        estimatedPlayTime: 8,
        tags: ['cards', 'matching'],
    },
    {
        id: 'cribbage',
        name: 'Cribbage',
        description: 'Traditional pegging card game',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'hard',
        thumbnail: '/games/cribbage.jpg',
        estimatedPlayTime: 12,
        tags: ['cards', 'scoring'],
    },
    {
        id: 'pyramid-solitaire',
        name: 'Pyramid Solitaire',
        description: 'Remove pairs that add to 13',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'easy',
        thumbnail: '/games/pyramid.jpg',
        estimatedPlayTime: 5,
        tags: ['cards', 'math'],
    },

    // Word Games (10 games)
    {
        id: 'word-search',
        name: 'Word Search',
        description: 'Find hidden words in letter grid',
        category: 'word-games',
        ageGroup: 'all-ages',
        difficulty: 'easy',
        thumbnail: '/games/wordsearch.jpg',
        estimatedPlayTime: 5,
        tags: ['words', 'search'],
        premium: true,
    },
    {
        id: 'crossword-easy',
        name: 'Crossword Puzzle',
        description: 'Classic crossword with clues',
        category: 'word-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/crossword.jpg',
        estimatedPlayTime: 15,
        tags: ['words', 'vocabulary'],
    },
    {
        id: 'anagram-challenge',
        name: 'Anagram Master',
        description: 'Unscramble letters to form words',
        category: 'word-games',
        ageGroup: 'all-ages',
        difficulty: 'medium',
        thumbnail: '/games/anagram.jpg',
        estimatedPlayTime: 4,
        tags: ['words', 'puzzle'],
    },
    {
        id: 'word-ladder',
        name: 'Word Ladder',
        description: 'Change one letter at a time',
        category: 'word-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/ladder.jpg',
        estimatedPlayTime: 6,
        tags: ['words', 'logic'],
    },
    {
        id: 'hangman',
        name: 'Hangman',
        description: 'Guess the word letter by letter',
        category: 'word-games',
        ageGroup: 'all-ages',
        difficulty: 'easy',
        thumbnail: '/games/hangman.jpg',
        estimatedPlayTime: 3,
        tags: ['words', 'guessing'],
    },
    {
        id: 'spelling-bee',
        name: 'Spelling Bee',
        description: 'Make words from given letters',
        category: 'word-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/spelling.jpg',
        estimatedPlayTime: 10,
        tags: ['words', 'vocabulary'],
    },
    {
        id: 'boggle',
        name: 'Word Grid',
        description: 'Find words in connected letters',
        category: 'word-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/boggle.jpg',
        estimatedPlayTime: 5,
        tags: ['words', 'speed'],
    },
    {
        id: 'cryptogram',
        name: 'Cryptogram',
        description: 'Decode encrypted quotes',
        category: 'word-games',
        ageGroup: 'seniors',
        difficulty: 'hard',
        thumbnail: '/games/crypto.jpg',
        estimatedPlayTime: 12,
        tags: ['words', 'cipher', 'logic'],
    },
    {
        id: 'word-association',
        name: 'Word Association',
        description: 'Connect related words',
        category: 'word-games',
        ageGroup: 'seniors',
        difficulty: 'easy',
        thumbnail: '/games/association.jpg',
        estimatedPlayTime: 4,
        tags: ['words', 'memory'],
    },
    {
        id: 'vocabulary-builder',
        name: 'Vocabulary Builder',
        description: 'Learn and match word definitions',
        category: 'word-games',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/vocab.jpg',
        estimatedPlayTime: 8,
        tags: ['words', 'learning'],
    },

    // Relaxation & Visual (10 games)
    {
        id: 'jigsaw-easy',
        name: 'Jigsaw Puzzle (24 pieces)',
        description: 'Relaxing picture puzzles',
        category: 'brain-training',
        ageGroup: 'all-ages',
        difficulty: 'easy',
        thumbnail: '/games/jigsaw.jpg',
        estimatedPlayTime: 10,
        tags: ['puzzle', 'relaxing'],
    },
    {
        id: 'jigsaw-medium',
        name: 'Jigsaw Puzzle (48 pieces)',
        description: 'Medium difficulty picture puzzles',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/jigsaw-med.jpg',
        estimatedPlayTime: 20,
        tags: ['puzzle', 'relaxing'],
    },
    {
        id: 'jigsaw-hard',
        name: 'Jigsaw Puzzle (100 pieces)',
        description: 'Challenging picture puzzles',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'hard',
        thumbnail: '/games/jigsaw-hard.jpg',
        estimatedPlayTime: 35,
        tags: ['puzzle', 'challenge'],
    },
    {
        id: 'coloring-mandala',
        name: 'Mandala Coloring',
        description: 'Color beautiful mandala patterns',
        category: 'brain-training',
        ageGroup: 'all-ages',
        difficulty: 'easy',
        thumbnail: '/games/mandala.jpg',
        estimatedPlayTime: 15,
        tags: ['art', 'relaxing', 'creative'],
    },
    {
        id: 'tangram',
        name: 'Tangram Puzzles',
        description: 'Arrange shapes to match silhouettes',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/tangram.jpg',
        estimatedPlayTime: 5,
        tags: ['shapes', 'spatial'],
    },
    {
        id: 'match-three-zen',
        name: 'Zen Match',
        description: 'Relaxing match-3 puzzle',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'easy',
        thumbnail: '/games/zen-match.jpg',
        estimatedPlayTime: 8,
        tags: ['matching', 'relaxing'],
    },
    {
        id: 'tile-matching',
        name: 'Tile Matching',
        description: 'Match pairs of decorative tiles',
        category: 'classic-games',
        ageGroup: 'seniors',
        difficulty: 'easy',
        thumbnail: '/games/tiles.jpg',
        estimatedPlayTime: 6,
        tags: ['matching', 'visual'],
    },
    {
        id: 'hidden-objects',
        name: 'Hidden Objects',
        description: 'Find items in detailed scenes',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'medium',
        thumbnail: '/games/hidden.jpg',
        estimatedPlayTime: 10,
        tags: ['visual', 'observation'],
    },
    {
        id: 'mosaic-puzzles',
        name: 'Mosaic Puzzles',
        description: 'Create pictures from colored tiles',
        category: 'brain-training',
        ageGroup: 'seniors',
        difficulty: 'easy',
        thumbnail: '/games/mosaic.jpg',
        estimatedPlayTime: 12,
        tags: ['art', 'puzzle', 'relaxing'],
    },
    {
        id: 'dot-connect',
        name: 'Connect the Dots',
        description: 'Reveal images by connecting numbered dots',
        category: 'brain-training',
        ageGroup: 'all-ages',
        difficulty: 'easy',
        thumbnail: '/games/dots.jpg',
        estimatedPlayTime: 4,
        tags: ['visual', 'sequence'],
    },

    // ===== KIDS GAMES (50) =====

    // Learning & Education (15 games)
    {
        id: 'counting-fun',
        name: 'Counting Fun',
        description: 'Count colorful objects 1-20',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/counting.jpg',
        estimatedPlayTime: 3,
        tags: ['math', 'numbers', 'educational'],
        premium: true,
    },
    {
        id: 'abc-tracing',
        name: 'ABC Tracing',
        description: 'Learn to write letters A-Z',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/abc.jpg',
        estimatedPlayTime: 4,
        tags: ['letters', 'writing'],
    },
    {
        id: 'shape-matching',
        name: 'Shape Match',
        description: 'Match shapes and learn geometry',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/shapes.jpg',
        estimatedPlayTime: 3,
        tags: ['shapes', 'matching'],
    },
    {
        id: 'color-learning',
        name: 'Color Learning',
        description: 'Learn colors with fun activities',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/colors.jpg',
        estimatedPlayTime: 3,
        tags: ['colors', 'educational'],
    },
    {
        id: 'basic-math-addition',
        name: 'Addition Fun',
        description: 'Practice adding numbers 1-10',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/addition.jpg',
        estimatedPlayTime: 4,
        tags: ['math', 'addition'],
    },
    {
        id: 'basic-math-subtraction',
        name: 'Subtraction Adventure',
        description: 'Learn subtraction with fun visuals',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/subtraction.jpg',
        estimatedPlayTime: 4,
        tags: ['math', 'subtraction'],
    },
    {
        id: 'clock-reading',
        name: 'Tell the Time',
        description: 'Learn to read analog clocks',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'medium',
        thumbnail: '/games/clock.jpg',
        estimatedPlayTime: 5,
        tags: ['time', 'educational'],
    },
    {
        id: 'money-counting',
        name: 'Money Counting',
        description: 'Count coins and make change',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'medium',
        thumbnail: '/games/money.jpg',
        estimatedPlayTime: 5,
        tags: ['math', 'money'],
    },
    {
        id: 'rhyming-words',
        name: 'Rhyme Time',
        description: 'Match words that rhyme',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/rhyme.jpg',
        estimatedPlayTime: 3,
        tags: ['words', 'reading'],
    },
    {
        id: 'sight-words',
        name: 'Sight Words',
        description: 'Learn common reading words',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/sight-words.jpg',
        estimatedPlayTime: 4,
        tags: ['reading', 'words'],
    },
    {
        id: 'phonics-sounds',
        name: 'Phonics Fun',
        description: 'Learn letter sounds and blends',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/phonics.jpg',
        estimatedPlayTime: 4,
        tags: ['reading', 'sounds'],
    },
    {
        id: 'pattern-completion',
        name: 'Pattern Fun',
        description: 'Complete colorful patterns',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/pattern-kids.jpg',
        estimatedPlayTime: 3,
        tags: ['patterns', 'logic'],
    },
    {
        id: 'animal-sounds',
        name: 'Animal Sounds',
        description: 'Match animals to their sounds',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/animal-sounds.jpg',
        estimatedPlayTime: 3,
        tags: ['animals', 'sounds'],
    },
    {
        id: 'seasons-weather',
        name: 'Seasons & Weather',
        description: 'Learn about seasons and weather',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/seasons.jpg',
        estimatedPlayTime: 4,
        tags: ['science', 'educational'],
    },
    {
        id: 'body-parts',
        name: 'Body Parts',
        description: 'Learn parts of the body',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/body.jpg',
        estimatedPlayTime: 3,
        tags: ['science', 'educational'],
    },

    // Action & Arcade (20 games)
    {
        id: 'bubble-pop',
        name: 'Bubble Pop',
        description: 'Pop colorful rising bubbles',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/bubbles.jpg',
        estimatedPlayTime: 2,
        tags: ['arcade', 'colorful'],
        premium: true,
    },
    {
        id: 'whack-a-mole',
        name: 'Whack-a-Mole',
        description: 'Test your reflexes!',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/whack.jpg',
        estimatedPlayTime: 2,
        tags: ['reflexes', 'quick'],
        premium: true,
    },
    {
        id: 'catch-the-fruit',
        name: 'Fruit Catcher',
        description: 'Catch falling fruits in basket',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/fruit.jpg',
        estimatedPlayTime: 2,
        tags: ['arcade', 'catching'],
        premium: true,
    },
    {
        id: 'jump-adventure',
        name: 'Jump Adventure',
        description: 'Jump over obstacles',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/jump.jpg',
        estimatedPlayTime: 3,
        tags: ['platformer', 'adventure'],
    },
    {
        id: 'balloon-pop',
        name: 'Balloon Pop',
        description: 'Pop balloons before they float away',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/balloon.jpg',
        estimatedPlayTime: 2,
        tags: ['arcade', 'popping'],
    },
    {
        id: 'endless-runner',
        name: 'Endless Runner',
        description: 'Run and collect stars',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'medium',
        thumbnail: '/games/runner.jpg',
        estimatedPlayTime: 3,
        tags: ['running', 'endless'],
    },
    {
        id: 'space-shooter-kids',
        name: 'Space Adventure',
        description: 'Friendly space shooting game',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/space-kids.jpg',
        estimatedPlayTime: 3,
        tags: ['space', 'shooting'],
    },
    {
        id: 'dodge-obstacles',
        name: 'Dodge & Weave',
        description: 'Dodge moving obstacles',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'medium',
        thumbnail: '/games/dodge.jpg',
        estimatedPlayTime: 2,
        tags: ['reflexes', 'dodging'],
    },
    {
        id: 'stack-blocks',
        name: 'Stack Master',
        description: 'Stack blocks as high as you can',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/stack.jpg',
        estimatedPlayTime: 3,
        tags: ['stacking', 'balance'],
    },
    {
        id: 'flying-game',
        name: 'Flappy Bird Style',
        description: 'Fly through obstacles',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'medium',
        thumbnail: '/games/flappy.jpg',
        estimatedPlayTime: 2,
        tags: ['flying', 'timing'],
    },
    {
        id: 'treasure-hunt',
        name: 'Treasure Hunt',
        description: 'Find hidden treasures',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/treasure.jpg',
        estimatedPlayTime: 4,
        tags: ['adventure', 'exploring'],
    },
    {
        id: 'racing-simple',
        name: 'Simple Racer',
        description: 'Easy racing game for kids',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/racing.jpg',
        estimatedPlayTime: 3,
        tags: ['racing', 'cars'],
    },
    {
        id: 'candy-collect',
        name: 'Candy Collector',
        description: 'Collect candies while avoiding obstacles',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/candy.jpg',
        estimatedPlayTime: 3,
        tags: ['collecting', 'arcade'],
    },
    {
        id: 'animal-memory',
        name: 'Animal Memory',
        description: 'Match cute animal pairs',
        category: 'learning-fun',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/animals.jpg',
        estimatedPlayTime: 3,
        tags: ['animals', 'memory'],
    },
    {
        id: 'simon-says',
        name: 'Memory Simon',
        description: 'Repeat the color sequence',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'medium',
        thumbnail: '/games/simon.jpg',
        estimatedPlayTime: 3,
        tags: ['memory', 'sequence'],
    },
    {
        id: 'tap-the-mole',
        name: 'Tap Speed',
        description: 'Tap as fast as you can',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/tap.jpg',
        estimatedPlayTime: 2,
        tags: ['speed', 'tapping'],
    },
    {
        id: 'break-the-bricks',
        name: 'Brick Breaker',
        description: 'Break colorful bricks with ball',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'medium',
        thumbnail: '/games/bricks.jpg',
        estimatedPlayTime: 5,
        tags: ['arcade', 'classic'],
    },
    {
        id: 'fish-feeding',
        name: 'Feed the Fish',
        description: 'Feed hungry fish in aquarium',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/fish.jpg',
        estimatedPlayTime: 3,
        tags: ['animals', 'caring'],
    },
    {
        id: 'penguin-slide',
        name: 'Penguin Slide',
        description: 'Help penguin slide down icy hills',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/penguin.jpg',
        estimatedPlayTime: 3,
        tags: ['animals', 'sliding'],
    },
    {
        id: 'butterfly-catch',
        name: 'Butterfly Catcher',
        description: 'Catch beautiful butterflies',
        category: 'action-arcade',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/butterfly.jpg',
        estimatedPlayTime: 3,
        tags: ['nature', 'catching'],
    },

    // Creative Play (15 games)
    {
        id: 'coloring-book',
        name: 'Coloring Book',
        description: 'Color fun pictures',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/coloring.jpg',
        estimatedPlayTime: 10,
        tags: ['art', 'creative'],
        premium: true,
    },
    {
        id: 'drawing-pad',
        name: 'Drawing Pad',
        description: 'Free drawing with colors',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/drawing.jpg',
        estimatedPlayTime: 15,
        tags: ['art', 'creative'],
    },
    {
        id: 'sticker-scene',
        name: 'Sticker Scenes',
        description: 'Create scenes with stickers',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/stickers.jpg',
        estimatedPlayTime: 10,
        tags: ['creative', 'decorating'],
    },
    {
        id: 'dress-up',
        name: 'Dress Up Fun',
        description: 'Dress up characters with outfits',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/dress-up.jpg',
        estimatedPlayTime: 8,
        tags: ['dress-up', 'creative'],
    },
    {
        id: 'music-maker',
        name: 'Music Maker',
        description: 'Create music with instruments',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/music.jpg',
        estimatedPlayTime: 10,
        tags: ['music', 'creative'],
    },
    {
        id: 'pixel-art',
        name: 'Pixel Art',
        description: 'Create pixel art pictures',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'medium',
        thumbnail: '/games/pixel.jpg',
        estimatedPlayTime: 12,
        tags: ['art', 'pixels'],
    },
    {
        id: 'face-maker',
        name: 'Silly Face Maker',
        description: 'Create funny faces',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/faces.jpg',
        estimatedPlayTime: 5,
        tags: ['creative', 'funny'],
    },
    {
        id: 'room-decorator',
        name: 'Room Decorator',
        description: 'Design and decorate rooms',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/room.jpg',
        estimatedPlayTime: 12,
        tags: ['design', 'decorating'],
    },
    {
        id: 'cake-decorator',
        name: 'Cake Decorator',
        description: 'Decorate yummy cakes',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/cake.jpg',
        estimatedPlayTime: 8,
        tags: ['food', 'decorating'],
    },
    {
        id: 'pet-salon',
        name: 'Pet Salon',
        description: 'Groom and style cute pets',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/salon.jpg',
        estimatedPlayTime: 10,
        tags: ['animals', 'grooming'],
    },
    {
        id: 'garden-planting',
        name: 'Garden Game',
        description: 'Plant and grow a garden',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/garden.jpg',
        estimatedPlayTime: 12,
        tags: ['nature', 'growing'],
    },
    {
        id: 'pizza-maker',
        name: 'Pizza Maker',
        description: 'Make custom pizzas',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/pizza.jpg',
        estimatedPlayTime: 7,
        tags: ['food', 'creating'],
    },
    {
        id: 'band-creator',
        name: 'Band Creator',
        description: 'Create your own band',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/band.jpg',
        estimatedPlayTime: 10,
        tags: ['music', 'creative'],
    },
    {
        id: 'stamp-art',
        name: 'Stamp Art',
        description: 'Create art with stamps',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/stamps.jpg',
        estimatedPlayTime: 10,
        tags: ['art', 'stamps'],
    },
    {
        id: 'pattern-designer',
        name: 'Pattern Designer',
        description: 'Design colorful patterns',
        category: 'creative-play',
        ageGroup: 'kids',
        difficulty: 'easy',
        thumbnail: '/games/pattern-design.jpg',
        estimatedPlayTime: 10,
        tags: ['art', 'patterns'],
    },
];

// Helper functions
export function getGamesByCategory(categoryId: string): Game[] {
    return GAMES.filter(game => game.category === categoryId);
}

export function getGamesByAgeGroup(ageGroup: AgeGroup): Game[] {
    if (ageGroup === 'all-ages') {
        return GAMES;
    }
    return GAMES.filter(game => game.ageGroup === ageGroup || game.ageGroup === 'all-ages');
}

export function getGameById(id: string): Game | undefined {
    return GAMES.find(game => game.id === id);
}

export function getFeaturedGames(): Game[] {
    return GAMES.filter(game => game.premium).slice(0, 6);
}

export function getGameStats() {
    return {
        total: GAMES.length,
        seniors: GAMES.filter(g => g.ageGroup === 'seniors').length,
        kids: GAMES.filter(g => g.ageGroup === 'kids').length,
        allAges: GAMES.filter(g => g.ageGroup === 'all-ages').length,
    };
}
